name: pokemon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  json_annotation: ^3.1.1
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  bloc_pattern: ^2.5.1
  rxdart: ^0.24.0
  firebase_crashlytics: "^0.4.0+1"
  firebase_core : ^0.7.0

dev_dependencies:
  lint: ^1.3.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
